//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNCSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVendor
    {
        public long ID { get; set; }
        public int companyID { get; set; }
        public string ListID { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
        public Nullable<int> EditSequence { get; set; }
        public string Name { get; set; }
        public string ArName { get; set; }
        public string FullName { get; set; }
        public string IsActive { get; set; }
        public Nullable<int> Sublevel { get; set; }
        public string CompanyName { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string BillAddress1 { get; set; }
        public string BillAddress2 { get; set; }
        public string Phone { get; set; }
        public string AltPhone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
        public string AltContact { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> TotalBalance { get; set; }
        public string AccountNumber { get; set; }
        public string CreditLimit { get; set; }
        public string PrintChequeAs { get; set; }
        public string Cc { get; set; }
        public string ActName { get; set; }
        public string BankName { get; set; }
        public string ActNumber { get; set; }
        public string Branch { get; set; }
        public string type { get; set; }
    }
}
